# Generated by Django 5.2.7 on 2025-10-12 10:54

import django.core.validators
import seafood.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(help_text='Format: 41XXXXXX (généré automatiquement)', max_length=8, unique=True, verbose_name='Code Comptable')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_type', models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise'), ('organization', 'Organisation')], default='individual', max_length=20, verbose_name='Type de client')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('mobile', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de portable doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Portable')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Mauritanie', max_length=100, verbose_name='Pays')),
                ('trade_register', models.CharField(blank=True, max_length=50, verbose_name='Numéro de registre de commerce')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identification fiscal")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, help_text='Informations supplémentaires sur le client', verbose_name='Observations')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=seafood.models.client_logo_path, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accounting_code'], name='seafood_cli_account_76ce97_idx'), models.Index(fields=['status'], name='seafood_cli_status_210cb4_idx')],
            },
        ),
    ]
