# Generated by Django 5.2.7 on 2025-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Accepté'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
