# Generated by Django 5.2.7 on 2025-10-12 10:54

from django.db import migrations


def copy_clients_from_operations(apps, schema_editor):
    """Copier les données des clients de operations vers seafood"""
    # Récupérer les modèles
    OperationsClient = apps.get_model('operations', 'Client')
    SeafoodClient = apps.get_model('seafood', 'Client')

    # Copier tous les clients
    for old_client in OperationsClient.objects.all():
        SeafoodClient.objects.create(
            id=old_client.id,
            accounting_code=old_client.accounting_code,
            name=old_client.name,
            client_type=old_client.client_type,
            website=old_client.website,
            responsible=old_client.responsible,
            mobile=old_client.mobile,
            phone=old_client.phone,
            email=old_client.email,
            address=old_client.address,
            city=old_client.city,
            postal_code=old_client.postal_code,
            country=old_client.country,
            trade_register=old_client.trade_register,
            tax_id=old_client.tax_id,
            status=old_client.status,
            observations=old_client.observations,
            logo=old_client.logo,
            created_at=old_client.created_at,
            updated_at=old_client.updated_at,
        )


def reverse_copy(apps, schema_editor):
    """Supprimer les clients de seafood en cas de rollback"""
    SeafoodClient = apps.get_model('seafood', 'Client')
    SeafoodClient.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0002_client'),
        ('operations', '0001_initial'),  # Dépendance sur operations
    ]

    operations = [
        migrations.RunPython(copy_clients_from_operations, reverse_copy),
    ]
