# Generated by Django 5.2.7 on 2025-10-14 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0002_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_payments', to='seafood.cashbox', verbose_name='Caisse de paiement'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cashbox', 'Caisse'), ('bank', 'Compte bancaire')], max_length=20, null=True, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='category',
            field=models.CharField(choices=[('classic', 'Classique'), ('bank_mobile', 'Banque mobile'), ('neo_bank', 'Néo-banque'), ('payment_gateway', 'Passerelle de paiement'), ('e_wallet', 'Portefeuille électronique')], default='classic', max_length=20, verbose_name='Catégorie'),
        ),
    ]
