# Generated by Django 5.2.7 on 2025-10-12 20:46

import django.core.validators
import seafood.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0003_auto_20251012_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_code', models.CharField(help_text='Format: 40XXXXXX (généré automatiquement)', max_length=8, unique=True, verbose_name='Compte Comptable')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('category', models.CharField(choices=[('logistics', 'Logistics, Transportation & Warehousing'), ('consulting', 'Consulting'), ('engineering', 'Engineering'), ('finance', 'Finance & Insurance'), ('manufacturing', 'Manufacturing'), ('mechanics', 'Mechanics'), ('mining', 'Mining'), ('construction', 'Construction'), ('administration', 'Administration, Business Support'), ('fish_food', 'Fish & Food'), ('agriculture', 'Agriculture, Forestry, Fishing and Hunting'), ('educational', 'Educational Services'), ('professional', 'Professional, Scientific and Technical Services'), ('advisory', 'Advisory and Financial Services'), ('industrial', 'Industrial Machinery, Gas and Chemicals'), ('retail', 'Retail Market Reports')], max_length=20, verbose_name="Catégorie (Secteur d'activité)")),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identification fiscale")),
                ('trade_register', models.CharField(blank=True, max_length=50, verbose_name='Numéro de registre de commerce')),
                ('payment_terms', models.PositiveIntegerField(default=30, help_text='Nombre de jours pour le paiement', verbose_name='Termes de paiement (jours)')),
                ('contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone de contact')),
                ('mobile', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de portable doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone mobile')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Mauritanie', max_length=100, verbose_name='Pays')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=seafood.models.supplier_logo_path, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accounting_code'], name='seafood_sup_account_c57575_idx'), models.Index(fields=['status'], name='seafood_sup_status_d673d4_idx'), models.Index(fields=['category'], name='seafood_sup_categor_4d8b88_idx')],
            },
        ),
    ]
