# Generated by Django 5.2.7 on 2025-10-14 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0003_purchaseorder_payment_cashbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la caisse', verbose_name='Description'),
        ),
        migrations.AddIndex(
            model_name='cashbox',
            index=models.Index(fields=['status'], name='seafood_cas_status_30c4a8_idx'),
        ),
    ]
