# Generated by Django 5.2.7 on 2025-10-13 11:18

import django.db.models.deletion
import seafood.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0004_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('logistics', 'Logistiques'), ('manufacturing', 'Fabrication'), ('mining', 'Exploitation minière'), ('construction', 'Fabrication'), ('administration', 'Administration'), ('fish_food', 'Pêche & alimentation'), ('other', 'Autre')], max_length=20, verbose_name="Catégorie (Secteur d'activité)"),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_identifier', models.CharField(help_text='Format: BNK + 6 chiffres (généré automatiquement)', max_length=9, unique=True, verbose_name='Identifiant bancaire')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Nom de la banque')),
                ('account_number', models.CharField(max_length=50, verbose_name='Numéro de compte')),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, verbose_name='IBAN')),
                ('agency', models.CharField(blank=True, max_length=200, verbose_name='Agence')),
                ('account_type', models.CharField(choices=[('checking', 'Compte courant'), ('savings', 'Compte épargne'), ('merchant', 'Compte marchand'), ('virtual', 'Compte virtuel')], default='checking', max_length=20, verbose_name='Type de compte')),
                ('category', models.CharField(choices=[('classic', 'Classique'), ('mobile_money', 'Mobile Money'), ('neo_bank', 'Néo-banque'), ('payment_gateway', 'Passerelle de paiement'), ('e_wallet', 'Portefeuille électronique')], default='classic', max_length=20, verbose_name='Catégorie')),
                ('currency', models.CharField(choices=[('MRU', 'Ouguiya (MRU)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Dollar canadien (CAD)')], default='MRU', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('closed', 'Fermé'), ('frozen', 'Gelé')], default='active', max_length=20, verbose_name='Statut')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Titulaire du compte')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('rib_scan', models.FileField(blank=True, help_text="Relevé d'Identité Bancaire", null=True, upload_to=seafood.models.bank_account_attachment_path, verbose_name='Scan RIB')),
                ('contract', models.FileField(blank=True, null=True, upload_to=seafood.models.bank_account_attachment_path, verbose_name='Contrat')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Solde actuel')),
                ('account_opening_date', models.DateField(verbose_name="Date d'ouverture du compte")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_code', models.CharField(help_text='Code unique de la caisse', max_length=20, unique=True, verbose_name='Dossier')),
                ('prefix', models.CharField(help_text='Préfixe pour la numérotation des documents', max_length=10, verbose_name='Préfixe')),
                ('description', models.TextField(help_text='Description de la caisse', verbose_name='Description')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Solde actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text='Numéro unique du bon de commande (généré automatiquement)', max_length=20, unique=True, verbose_name='Numéro PO')),
                ('po_date', models.DateField(verbose_name='Date PO')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('file', models.FileField(blank=True, null=True, upload_to=seafood.models.purchase_order_file_path, verbose_name='Fichier')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Montant taxe')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sous-total')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seafood.bankaccount', verbose_name='Compte bancaire de paiement')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seafood.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(help_text='Numéro sur 6 chiffres (généré automatiquement)', max_length=6, unique=True, verbose_name='Numéro PR')),
                ('pr_date', models.DateField(verbose_name='Date PR')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('pieces', 'Pièces'), ('bags', 'Sacs'), ('boxes', 'Boîtes'), ('foot', 'Pieds'), ('meter', 'Mètres'), ('pairs', 'Paires'), ('reams', 'Rames'), ('rolls', 'Rouleaux'), ('sets', 'Ensembles'), ('square_meters', 'Mètres carrés'), ('square_feet', 'Pieds carrés'), ('tons', 'Tonnes')], default='pieces', max_length=20, verbose_name='Unité')),
                ('requester_first_name', models.CharField(max_length=100, verbose_name='Prénom du demandeur')),
                ('requester_last_name', models.CharField(max_length=100, verbose_name='Nom du demandeur')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('requester_phone', models.CharField(max_length=17, verbose_name='Téléphone du demandeur')),
                ('deadline', models.DateField(verbose_name='Échéance de la demande')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('proforma', 'Proforma'), ('approved', 'Accepté'), ('rejected', 'Rejeté')], default='proforma', max_length=20, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, help_text='Obligatoire si le statut est "Rejeté"', verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seafood.cashbox', verbose_name='Référence caisse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Demande d'achat",
                'verbose_name_plural': "Demandes d'achat",
                'ordering': ['-pr_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_identifier'], name='seafood_ban_bank_id_0309be_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['status'], name='seafood_ban_status_4321bc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='seafood_pur_po_numb_d6d579_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='seafood_pur_status_449503_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_date'], name='seafood_pur_po_date_7a7176_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['pr_number'], name='seafood_pur_pr_numb_e4e46e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='seafood_pur_status_bf78d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['pr_date'], name='seafood_pur_pr_date_0e8432_idx'),
        ),
    ]
