# Generated by Django 5.2.7 on 2025-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0004_cashbox_status_alter_cashbox_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='folder_code',
            field=models.CharField(help_text="Nom de la caisse (ex: Technologie de l'information)", max_length=200, verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='prefix',
            field=models.CharField(help_text='Préfixe unique pour la numérotation des documents (max 6 caractères)', max_length=6, unique=True, verbose_name='Préfixe'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='transaction_number',
            field=models.CharField(help_text='Format: TRXXXXXXX (généré automatiquement)', max_length=20, unique=True, verbose_name='Numéro de transaction'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise'), ('restaurant ', 'Restaurant'), ('organization', 'Organisation')], default='individual', max_length=20, verbose_name='Type de client'),
        ),
    ]
