# Generated by Django 5.2.7 on 2025-10-13 13:18

import django.db.models.deletion
import seafood.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0005_alter_supplier_category_bankaccount_cashbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashboxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(help_text='Format: TRX-XXXXXX (généré automatiquement)', max_length=20, unique=True, verbose_name='Numéro de transaction')),
                ('transaction_type', models.CharField(choices=[('in', 'Entrée (Alimentation)'), ('out', 'Sortie')], max_length=3, verbose_name='Type de transaction')),
                ('source', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('cash_deposit', 'Dépôt espèces'), ('purchase_order', 'Bon de commande'), ('other', 'Autre')], max_length=20, verbose_name='Source/Mode')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('transaction_date', models.DateField(verbose_name='Date de transaction')),
                ('description', models.TextField(help_text='Motif de la transaction', verbose_name='Description')),
                ('justification', models.FileField(blank=True, help_text='Document justifiant la transaction (optionnel)', null=True, upload_to=seafood.models.cashbox_transaction_attachment_path, verbose_name='Pièce justificative')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde après transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.bankaccount', verbose_name='Compte bancaire')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='seafood.cashbox', verbose_name='Caisse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Transaction de caisse',
                'verbose_name_plural': 'Transactions de caisse',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_number'], name='seafood_cas_transac_20d896_idx'), models.Index(fields=['cashbox', 'transaction_date'], name='seafood_cas_cashbox_43f60c_idx'), models.Index(fields=['transaction_type'], name='seafood_cas_transac_074b8b_idx')],
            },
        ),
    ]
