# Generated by Django 5.2.7 on 2025-10-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0006_cashboxtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtransaction',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du chèque/versement'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='check_number',
            field=models.CharField(blank=True, help_text='Numéro du chèque ou du versement', max_length=50, verbose_name='Numéro de chèque/versement'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='issuing_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_transactions', to='seafood.bankaccount', verbose_name='Banque émettrice'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Identifiant de la transaction (pour transfert mobile)', max_length=100, verbose_name='ID Transaction'),
        ),
        migrations.AddField(
            model_name='cashboxtransaction',
            name='transfer_reference',
            field=models.CharField(blank=True, help_text='Référence du virement bancaire', max_length=100, verbose_name='Référence de virement'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='source',
            field=models.CharField(choices=[('cash', 'Cash (Espèces)'), ('mobile_transfer', 'Transfert mobile'), ('check', 'Chèque'), ('deposit', 'Versement'), ('bank_transfer', 'Virement bancaire'), ('purchase_order', 'Bon de commande'), ('other', 'Autre')], max_length=20, verbose_name='Source/Mode'),
        ),
    ]
