# Generated by Django 5.2.7 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0007_cashboxtransaction_check_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashboxtransaction',
            name='purchase_order',
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='description',
            field=models.TextField(blank=True, help_text='Motif de la transaction', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cashboxtransaction',
            name='source',
            field=models.CharField(choices=[('cash', 'Cash (Espèces)'), ('mobile_transfer', 'Transfert mobile'), ('check', 'Chèque'), ('deposit', 'Versement'), ('bank_transfer', 'Virement bancaire'), ('other', 'Autre')], max_length=20, verbose_name='Source/Mode'),
        ),
    ]
