# Generated by Django 5.2.7 on 2025-10-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0008_remove_cashboxtransaction_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='unit',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('pieces', 'Pièces'), ('bags', 'Sacs'), ('boxes', 'Boîtes'), ('foot', 'Pieds'), ('meter', 'Mètres'), ('pairs', 'Paires'), ('reams', 'Rames'), ('rolls', 'Rouleaux'), ('sets', 'Ensembles'), ('square_meters', 'Mètres carrés'), ('square_feet', 'Pieds carrés'), ('tons', 'Tonnes')], default='pieces', max_length=20, verbose_name='Unité')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seafood.purchaserequest', verbose_name="Demande d'achat")),
            ],
            options={
                'verbose_name': "Ligne de demande d'achat",
                'verbose_name_plural': "Lignes de demandes d'achat",
                'ordering': ['order', 'id'],
            },
        ),
    ]
