# Generated by Django 5.2.7 on 2025-10-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0009_remove_purchaserequest_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Accepté'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut'),
        ),
    ]
