# Generated by Django 5.2.7 on 2025-10-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0010_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='cashbox',
        ),
    ]
