# Generated by Django 5.2.7 on 2025-10-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0011_remove_purchaserequest_cashbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('pieces', 'Pièces'), ('bags', 'Sacs'), ('boxes', 'Boîtes'), ('foot', 'Pieds'), ('meter', 'Mètres'), ('pairs', 'Paires'), ('reams', 'Rames'), ('rolls', 'Rouleaux'), ('sets', 'Ensembles'), ('square_meters', 'Mètres carrés'), ('square_feet', 'Pieds carrés'), ('tons', 'Tonnes')], default='pieces', max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix unitaire')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de taxe (%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seafood.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bons de commande',
                'ordering': ['order', 'id'],
            },
        ),
    ]
