# Generated by Django 5.2.7 on 2025-10-08 13:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role_is_active_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_avatar_path, verbose_name='Avatar'),
        ),
    ]
