# Generated by Django 5.2.7 on 2025-10-29 21:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seafood', '0006_alter_bankaccount_currency_prospect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie de poisson',
                'verbose_name_plural': 'Catégories de poissons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='Avatar')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_categories', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique sur 4 chiffres (1000-9999). Codes 1000-1010 réservés au système.', max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Code du service')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='État')),
                ('description', models.TextField(blank=True, verbose_name='Description du service')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant du service (peut être 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='operations.servicecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(help_text='Identifiant unique généré automatiquement (ex: 000001, 000002, ...)', max_length=20, unique=True, verbose_name='ID du LOT')),
                ('reception_date', models.DateField(verbose_name='Date de réception')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Poids du lot en kilogrammes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids (kg)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('accepted', 'Accepté'), ('in_progress', 'En traitement'), ('completed', 'Terminé'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='draft', max_length=50, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, help_text='Notes ou remarques sur la réception', verbose_name='Observations')),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet du lot', verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_notes', to='seafood.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_arrival_notes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('service_type', models.ForeignKey(help_text='Service à effectuer sur ce lot', on_delete=django.db.models.deletion.PROTECT, related_name='arrival_notes', to='operations.service', verbose_name='Type de service')),
            ],
            options={
                'verbose_name': "Note d'arrivée",
                'verbose_name_plural': "Notes d'arrivée",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lot_id'], name='operations__lot_id_052c39_idx'), models.Index(fields=['status'], name='operations__status_cfe479_idx'), models.Index(fields=['reception_date'], name='operations__recepti_0deae9_idx'), models.Index(fields=['client'], name='operations__client__2dd01d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='operations__code_8f53fb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='operations__status_ea1a07_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='operations__categor_c8d4ef_idx'),
        ),
    ]
