# Generated by Django 5.2.7 on 2025-10-22 16:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique sur 4 chiffres (1000-9999). Codes 1001-1010 réservés au système.', max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Code du service')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='État')),
                ('description', models.TextField(blank=True, verbose_name='Description du service')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant du service (peut être 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant')),
                ('category', models.CharField(choices=[('transfer', 'Transfert'), ('pelagic_freezing', 'Congélation pélagique'), ('cephalopod_freezing', 'Congélation de céphalopodes'), ('fresh_processing', 'Traitement et transformation des produits frais'), ('filleting', 'Filetage, découpe et emballage'), ('portioning', 'Préparation de portions calibrées')], max_length=50, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='operations__code_8f53fb_idx'), models.Index(fields=['status'], name='operations__status_ea1a07_idx'), models.Index(fields=['category'], name='operations__categor_955cff_idx')],
            },
        ),
    ]
