# Generated by Django 5.2.7 on 2025-10-23 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalnote',
            name='service_type',
            field=models.ForeignKey(help_text='Service à effectuer sur ce lot', on_delete=django.db.models.deletion.PROTECT, related_name='arrival_notes', to='operations.service', verbose_name='Type de service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(help_text='Code unique sur 4 chiffres (1000-9999). Codes 1000-1010 réservés au système.', max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Code du service'),
        ),
    ]
