# Generated by Django 5.2.7 on 2025-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_arrivalnote_service_type_alter_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('accepted', 'Accepté'), ('in_progress', 'En traitement'), ('completed', 'Terminé'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='draft', max_length=50, verbose_name='Statut'),
        ),
    ]
