# Generated by Django 5.2.7 on 2025-11-01 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_rename_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'verbose_name': 'Rapport de réception', 'verbose_name_plural': 'Rapports de réception'},
        ),
        migrations.AlterModelOptions(
            name='reportitem',
            options={'ordering': ['report', 'species'], 'verbose_name': 'Détail par espèce', 'verbose_name_plural': 'Détails par espèce'},
        ),
        migrations.RenameIndex(
            model_name='reception',
            new_name='operations__lot_id_9f8f00_idx',
            old_name='operations__lot_id_052c39_idx',
        ),
        migrations.RenameIndex(
            model_name='reception',
            new_name='operations__status_f133da_idx',
            old_name='operations__status_cfe479_idx',
        ),
        migrations.RenameIndex(
            model_name='reception',
            new_name='operations__recepti_7195be_idx',
            old_name='operations__recepti_0deae9_idx',
        ),
        migrations.RenameIndex(
            model_name='reception',
            new_name='operations__client__c995a1_idx',
            old_name='operations__client__2dd01d_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='operations__arrival_f5b69b_idx',
            old_name='operations__arrival_29e521_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='operations__status_fd21e6_idx',
            old_name='operations__status_d537ac_idx',
        ),
        migrations.RenameIndex(
            model_name='reportitem',
            new_name='operations__species_09cddb_idx',
            old_name='operations__species_bedab3_idx',
        ),
        migrations.AlterField(
            model_name='reception',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('accepted', 'Accepté'), ('completed', 'Terminé'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='draft', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='report',
            name='general_observation',
            field=models.TextField(blank=True, help_text='Remarques générales sur le rapport du lot', verbose_name='Observation générale'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du rapport'),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.report', verbose_name='Rapport de réception'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_date'], name='operations__report__1741d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportitem',
            index=models.Index(fields=['report'], name='operations__report__137c54_idx'),
        ),
    ]
