# Generated by Django 5.2.7 on 2025-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_arrivalnote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Catégorie'),
        ),
    ]
