# Generated by Django 5.2.7 on 2025-11-01 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_in_progress_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='arrival_note',
            field=models.ForeignKey(help_text='Sélectionner un lot dont le type de service est supérieur à 1003', on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='operations.reception', verbose_name="Lot (Note d'arrivée)"),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
