# Generated by Django 5.2.7 on 2025-10-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalnote',
            name='fish_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrival_notes', to='operations.fishcategory', verbose_name='Catégorie de poisson'),
        ),
    ]
