# Generated by Django 5.2.7 on 2025-11-01 20:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_rename_classification_to_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la sous-catégorie')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kilogrammes (optionnel)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Poids (kg)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix en devise locale (optionnel)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='État')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Sous-catégorie de service',
                'verbose_name_plural': 'Sous-catégories de services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='operations.servicecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_subcategories', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['category'], name='operations__categor_e59717_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubcategory',
            index=models.Index(fields=['status'], name='operations__status_ee5355_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicesubcategory',
            unique_together={('category', 'name')},
        ),
    ]
