# Generated by Django 5.2.7 on 2025-10-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_arrivalnote_fish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalnote',
            name='fish_category',
        ),
    ]
