# Generated by Django 5.2.7 on 2025-11-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_add_service_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='rejection_reason',
        ),
    ]
