# Generated by Django 5.2.7 on 2025-11-02 17:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_report_operations__classif_0930be_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Date du rapport')),
                ('pointer_full_name', models.CharField(help_text='Nom de la personne effectuant la classification', max_length=200, verbose_name='Nom complet du pointeur')),
                ('start_datetime', models.DateTimeField(help_text='Début de la classification', verbose_name='Date et heure de début')),
                ('end_datetime', models.DateTimeField(help_text='Fin de la classification', verbose_name='Date et heure de fin')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'operations_classification',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_count', models.PositiveIntegerField(help_text='Nombre de plats pour cette espèce', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de plats')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Poids total de cette espèce en kilogrammes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Détail de classification',
                'verbose_name_plural': 'Détails de classification',
                'db_table': 'operations_classificationitem',
                'ordering': ['classification', 'species'],
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classifications', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='classification',
            name='reception',
            field=models.ForeignKey(help_text="Note d'arrivée à classifier", on_delete=django.db.models.deletion.PROTECT, related_name='classifications', to='operations.reception', verbose_name='Réception (LOT)'),
        ),
        migrations.AddField(
            model_name='classificationitem',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.classification', verbose_name='Classification'),
        ),
        migrations.AddField(
            model_name='classificationitem',
            name='species',
            field=models.ForeignKey(help_text="Sous-catégorie de service représentant l'espèce", on_delete=django.db.models.deletion.PROTECT, related_name='classification_items', to='operations.servicesubcategory', verbose_name='Espèce'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['reception'], name='operations__recepti_51ba90_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['report_date'], name='operations__report__39e737_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['status'], name='operations__status_d537ac_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['start_datetime'], name='operations__start_d_ccf84a_idx'),
        ),
        migrations.AddIndex(
            model_name='classification',
            index=models.Index(fields=['end_datetime'], name='operations__end_dat_3b03c5_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationitem',
            index=models.Index(fields=['classification'], name='operations__classif_78ab73_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationitem',
            index=models.Index(fields=['species'], name='operations__species_4be7cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationitem',
            unique_together={('classification', 'species')},
        ),
    ]
