# Generated by Django 5.2.7 on 2025-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_classification_classificationitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Fin de la classification (rempli lors de la validation)', null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Début de la classification (rempli lors de la validation)', null=True, verbose_name='Date et heure de début'),
        ),
    ]
