# Generated by Django 5.2.7 on 2025-11-03 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_add_reference_chambre_and_tunnel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['-start_datetime', '-created_at'], 'verbose_name': 'Classification', 'verbose_name_plural': 'Classifications'},
        ),
        migrations.AlterField(
            model_name='classification',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Fin de la classification', null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='reference_chambre',
            field=models.CharField(blank=True, help_text='Référence de la chambre froide', max_length=100, null=True, verbose_name='Référence de la chambre'),
        ),
    ]
