# Generated by Django 5.2.7 on 2025-11-03 19:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_make_reference_chambre_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartonage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Start of boxing', verbose_name='Start date and time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='End of boxing', null=True, verbose_name='End date and time')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Boxing',
                'verbose_name_plural': 'Boxings',
                'db_table': 'operations_cartonage',
                'ordering': ['-start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartonageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_count', models.PositiveIntegerField(help_text='Number of boxes used for this species', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of boxes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Boxing detail',
                'verbose_name_plural': 'Boxing details',
                'db_table': 'operations_cartonageitem',
                'ordering': ['cartonage', 'species'],
            },
        ),
        migrations.AddField(
            model_name='cartonage',
            name='classification',
            field=models.ForeignKey(help_text='Completed classification to be boxed', on_delete=django.db.models.deletion.PROTECT, related_name='cartonages', to='operations.classification', verbose_name='Classification (LOT)'),
        ),
        migrations.AddField(
            model_name='cartonage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cartonages', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cartonageitem',
            name='cartonage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.cartonage', verbose_name='Boxing'),
        ),
        migrations.AddField(
            model_name='cartonageitem',
            name='species',
            field=models.ForeignKey(help_text='Service subcategory representing the species', on_delete=django.db.models.deletion.PROTECT, related_name='cartonage_items', to='operations.servicesubcategory', verbose_name='Species'),
        ),
        migrations.AddIndex(
            model_name='cartonage',
            index=models.Index(fields=['classification'], name='operations__classif_2ccfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='cartonage',
            index=models.Index(fields=['start_datetime'], name='operations__start_d_271a12_idx'),
        ),
        migrations.AddIndex(
            model_name='cartonage',
            index=models.Index(fields=['end_datetime'], name='operations__end_dat_2b6187_idx'),
        ),
        migrations.AddIndex(
            model_name='cartonage',
            index=models.Index(fields=['status'], name='operations__status_b644d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cartonageitem',
            index=models.Index(fields=['cartonage'], name='operations__cartona_320561_idx'),
        ),
        migrations.AddIndex(
            model_name='cartonageitem',
            index=models.Index(fields=['species'], name='operations__species_ac9cd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartonageitem',
            unique_together={('cartonage', 'species')},
        ),
    ]
