# Generated by Django 5.2.7 on 2025-11-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_add_cartonage_models'),
    ]

    operations = [
        # Rename Cartonage model to Packaging
        migrations.RenameModel(
            old_name='Cartonage',
            new_name='Packaging',
        ),

        # Rename CartonageItem model to PackagingItem
        migrations.RenameModel(
            old_name='CartonageItem',
            new_name='PackagingItem',
        ),

        # Rename the ForeignKey field in PackagingItem from 'cartonage' to 'packaging'
        migrations.RenameField(
            model_name='packagingitem',
            old_name='cartonage',
            new_name='packaging',
        ),

        # Update the table name for Packaging
        migrations.AlterModelTable(
            name='packaging',
            table='operations_packaging',
        ),

        # Update the table name for PackagingItem
        migrations.AlterModelTable(
            name='packagingitem',
            table='operations_packagingitem',
        ),

        # Update related_name for Classification -> Packaging relationship
        # This is handled by the models.py change, no migration operation needed
    ]
